
package com.agnity.ngin.sms.webservice.vpn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VpnServices", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VpnServices {


    /**
     * 
     * @param enterpriseDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createAccountDefaults", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreateAccountDefaults")
    @ResponseWrapper(localName = "createAccountDefaultsResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreateAccountDefaultsResponse")
    public WsResponse createAccountDefaults(
        @WebParam(name = "EnterpriseDetail", targetNamespace = "")
        EnterpriseDetail enterpriseDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param closedGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteCug", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DeleteCug")
    @ResponseWrapper(localName = "deleteCugResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DeleteCugResponse")
    public WsResponse deleteCug(
        @WebParam(name = "ClosedGroup", targetNamespace = "")
        ClosedGroup closedGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param servicePlan
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "configureServicePlan", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.ConfigureServicePlan")
    @ResponseWrapper(localName = "configureServicePlanResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.ConfigureServicePlanResponse")
    public WsResponse configureServicePlan(
        @WebParam(name = "ServicePlan", targetNamespace = "")
        ServicePlan servicePlan,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param pbxPnInfoDetails
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deletePbxPhone", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DeletePbxPhone")
    @ResponseWrapper(localName = "deletePbxPhoneResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DeletePbxPhoneResponse")
    public WsResponse deletePbxPhone(
        @WebParam(name = "PbxPnInfoDetails", targetNamespace = "")
        PbxPnInfoDetails pbxPnInfoDetails,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param closedGroupAssociation
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "dissociateCug", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DissociateCug")
    @ResponseWrapper(localName = "dissociateCugResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.DissociateCugResponse")
    public WsResponse dissociateCug(
        @WebParam(name = "ClosedGroupAssociation", targetNamespace = "")
        ClosedGroupAssociation closedGroupAssociation,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param closedGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createCug", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreateCug")
    @ResponseWrapper(localName = "createCugResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreateCugResponse")
    public WsResponse createCug(
        @WebParam(name = "ClosedGroup", targetNamespace = "")
        ClosedGroup closedGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param closedGroupAssociation
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "associateCug", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.AssociateCug")
    @ResponseWrapper(localName = "associateCugResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.AssociateCugResponse")
    public WsResponse associateCug(
        @WebParam(name = "ClosedGroupAssociation", targetNamespace = "")
        ClosedGroupAssociation closedGroupAssociation,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param pbxPnInfoDetails
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updatePbxPhone", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.UpdatePbxPhone")
    @ResponseWrapper(localName = "updatePbxPhoneResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.UpdatePbxPhoneResponse")
    public WsResponse updatePbxPhone(
        @WebParam(name = "PbxPnInfoDetails", targetNamespace = "")
        PbxPnInfoDetails pbxPnInfoDetails,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param pbxPnInfoDetails
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.vpn.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createPbxPhone", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreatePbxPhone")
    @ResponseWrapper(localName = "createPbxPhoneResponse", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.vpn.CreatePbxPhoneResponse")
    public WsResponse createPbxPhone(
        @WebParam(name = "PbxPnInfoDetails", targetNamespace = "")
        PbxPnInfoDetails pbxPnInfoDetails,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

}
