
package com.agnity.ngin.sms.webservice.vpn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VpnServices", targetNamespace = "http://vpn.webservice.sms.ngin.agnity.com/", wsdlLocation = "http://10.6.150.86:8003/vpn-ws/VpnServices/VpnServices?wsdl")
public class VpnServices_Service
    extends Service
{

    private final static URL VPNSERVICES_WSDL_LOCATION;
    private final static WebServiceException VPNSERVICES_EXCEPTION;
    private final static QName VPNSERVICES_QNAME = new QName("http://vpn.webservice.sms.ngin.agnity.com/", "VpnServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.150.86:8003/vpn-ws/VpnServices/VpnServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VPNSERVICES_WSDL_LOCATION = url;
        VPNSERVICES_EXCEPTION = e;
    }

    public VpnServices_Service() {
        super(__getWsdlLocation(), VPNSERVICES_QNAME);
    }

    public VpnServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VPNSERVICES_QNAME, features);
    }

    public VpnServices_Service(URL wsdlLocation) {
        super(wsdlLocation, VPNSERVICES_QNAME);
    }

    public VpnServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VPNSERVICES_QNAME, features);
    }

    public VpnServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VpnServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VpnServices
     */
    @WebEndpoint(name = "VpnServicesPort")
    public VpnServices getVpnServicesPort() {
        return super.getPort(new QName("http://vpn.webservice.sms.ngin.agnity.com/", "VpnServicesPort"), VpnServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VpnServices
     */
    @WebEndpoint(name = "VpnServicesPort")
    public VpnServices getVpnServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vpn.webservice.sms.ngin.agnity.com/", "VpnServicesPort"), VpnServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VPNSERVICES_EXCEPTION!= null) {
            throw VPNSERVICES_EXCEPTION;
        }
        return VPNSERVICES_WSDL_LOCATION;
    }

}
