
package com.agnity.ngin.sms.webservice.tollfree;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TollFreeSmsServices", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TollFreeSmsServices {


    /**
     * 
     * @param numberProfileList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFNumberProfileList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFNumberProfileList")
    @ResponseWrapper(localName = "getATFNumberProfileListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFNumberProfileListResponse")
    public WsResponse getATFNumberProfileList(
        @WebParam(name = "NumberProfileList", targetNamespace = "")
        NumberProfileList numberProfileList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanDelete
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFSuperRoutePlan", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFSuperRoutePlan")
    @ResponseWrapper(localName = "deleteATFSuperRoutePlanResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFSuperRoutePlanResponse")
    public WsResponse deleteATFSuperRoutePlan(
        @WebParam(name = "SuperRoutePlanDelete", targetNamespace = "")
        SuperRoutePlanDelete superRoutePlanDelete,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFTollFreeNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFTollFreeNumber")
    @ResponseWrapper(localName = "createATFTollFreeNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFTollFreeNumberResponse")
    public WsResponse createATFTollFreeNumber(
        @WebParam(name = "TollFreeNumber", targetNamespace = "")
        TollFreeNumber tollFreeNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param customProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFCustomProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFCustomProfile")
    @ResponseWrapper(localName = "createATFCustomProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFCustomProfileResponse")
    public WsResponse createATFCustomProfile(
        @WebParam(name = "CustomProfile", targetNamespace = "")
        CustomProfile customProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param servicePlan
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFServicePlan", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFServicePlan")
    @ResponseWrapper(localName = "updateATFServicePlanResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFServicePlanResponse")
    public WsResponse updateATFServicePlan(
        @WebParam(name = "ServicePlan", targetNamespace = "")
        ServicePlan servicePlan,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param customProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFCustomProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFCustomProfile")
    @ResponseWrapper(localName = "deleteATFCustomProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFCustomProfileResponse")
    public WsResponse deleteATFCustomProfile(
        @WebParam(name = "CustomProfile", targetNamespace = "")
        CustomProfile customProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param servicePlanSS7
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFServicePlanSS7", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFServicePlanSS7")
    @ResponseWrapper(localName = "updateATFServicePlanSS7Response", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFServicePlanSS7Response")
    public WsResponse updateATFServicePlanSS7(
        @WebParam(name = "ServicePlanSS7", targetNamespace = "")
        ServicePlanSS7 servicePlanSS7,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeSetting
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "configATFTollFreeSetting", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeSetting")
    @ResponseWrapper(localName = "configATFTollFreeSettingResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeSettingResponse")
    public WsResponse configATFTollFreeSetting(
        @WebParam(name = "TollFreeSetting", targetNamespace = "")
        TollFreeSetting tollFreeSetting,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param customProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFCustomProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFCustomProfile")
    @ResponseWrapper(localName = "updateATFCustomProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFCustomProfileResponse")
    public WsResponse updateATFCustomProfile(
        @WebParam(name = "CustomProfile", targetNamespace = "")
        CustomProfile customProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFSuperRoutePlan", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFSuperRoutePlan")
    @ResponseWrapper(localName = "createATFSuperRoutePlanResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFSuperRoutePlanResponse")
    public WsResponse createATFSuperRoutePlan(
        @WebParam(name = "SuperRoutePlanDetail", targetNamespace = "")
        SuperRoutePlanDetail superRoutePlanDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param terminatingNumberList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFTerminatingNumberList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTerminatingNumberList")
    @ResponseWrapper(localName = "getATFTerminatingNumberListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTerminatingNumberListResponse")
    public WsResponse getATFTerminatingNumberList(
        @WebParam(name = "TerminatingNumberList", targetNamespace = "")
        TerminatingNumberList terminatingNumberList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param terminatingNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFTerminatingNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFTerminatingNumber")
    @ResponseWrapper(localName = "createATFTerminatingNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFTerminatingNumberResponse")
    public WsResponse createATFTerminatingNumber(
        @WebParam(name = "TerminatingNumber", targetNamespace = "")
        TerminatingNumber terminatingNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeInfo
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "configATFTollFreeInfo", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeInfo")
    @ResponseWrapper(localName = "configATFTollFreeInfoResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeInfoResponse")
    public WsResponse configATFTollFreeInfo(
        @WebParam(name = "TollFreeInfo", targetNamespace = "")
        TollFreeInfo tollFreeInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFSuperRoutePlanGroup", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFSuperRoutePlanGroup")
    @ResponseWrapper(localName = "updateATFSuperRoutePlanGroupResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFSuperRoutePlanGroupResponse")
    public WsResponse updateATFSuperRoutePlanGroup(
        @WebParam(name = "SuperRoutePlanGroup", targetNamespace = "")
        SuperRoutePlanGroup superRoutePlanGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param terminatingNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFTerminatingNumberDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTerminatingNumberDetail")
    @ResponseWrapper(localName = "getATFTerminatingNumberDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTerminatingNumberDetailResponse")
    public WsResponse getATFTerminatingNumberDetail(
        @WebParam(name = "TerminatingNumber", targetNamespace = "")
        TerminatingNumber terminatingNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tfNumberDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFTollFreeDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTollFreeDetail")
    @ResponseWrapper(localName = "getATFTollFreeDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTollFreeDetailResponse")
    public WsResponse getATFTollFreeDetail(
        @WebParam(name = "TFNumberDetail", targetNamespace = "")
        TfNumberDetail tfNumberDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeNumberDeassign
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deassignATFTollFreeNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeassignATFTollFreeNumber")
    @ResponseWrapper(localName = "deassignATFTollFreeNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeassignATFTollFreeNumberResponse")
    public WsResponse deassignATFTollFreeNumber(
        @WebParam(name = "TollFreeNumberDeassign", targetNamespace = "")
        TollFreeNumber tollFreeNumberDeassign,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFSuperRoutePlanList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFSuperRoutePlanList")
    @ResponseWrapper(localName = "getATFSuperRoutePlanListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFSuperRoutePlanListResponse")
    public WsResponse getATFSuperRoutePlanList(
        @WebParam(name = "SuperRoutePlanList", targetNamespace = "")
        SuperRoutePlanList superRoutePlanList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param numberProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFNumberProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFNumberProfile")
    @ResponseWrapper(localName = "createATFNumberProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFNumberProfileResponse")
    public WsResponse createATFNumberProfile(
        @WebParam(name = "NumberProfile", targetNamespace = "")
        NumberProfile numberProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeNumberAssign
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "assignATFTollFreeNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.AssignATFTollFreeNumber")
    @ResponseWrapper(localName = "assignATFTollFreeNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.AssignATFTollFreeNumberResponse")
    public WsResponse assignATFTollFreeNumber(
        @WebParam(name = "TollFreeNumberAssign", targetNamespace = "")
        TollFreeNumber tollFreeNumberAssign,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFTollFreeNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFTollFreeNumber")
    @ResponseWrapper(localName = "updateATFTollFreeNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFTollFreeNumberResponse")
    public WsResponse updateATFTollFreeNumber(
        @WebParam(name = "TollFreeNumber", targetNamespace = "")
        TollFreeNumber tollFreeNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param terminatingNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFTerminatingNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFTerminatingNumber")
    @ResponseWrapper(localName = "deleteATFTerminatingNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFTerminatingNumberResponse")
    public WsResponse deleteATFTerminatingNumber(
        @WebParam(name = "TerminatingNumber", targetNamespace = "")
        TerminatingNumber terminatingNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFSuperRoutePlanGroup", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFSuperRoutePlanGroup")
    @ResponseWrapper(localName = "deleteATFSuperRoutePlanGroupResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFSuperRoutePlanGroupResponse")
    public WsResponse deleteATFSuperRoutePlanGroup(
        @WebParam(name = "SuperRoutePlanGroup", targetNamespace = "")
        SuperRoutePlanGroup superRoutePlanGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tfNumberList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFTollFreeList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTollFreeList")
    @ResponseWrapper(localName = "getATFTollFreeListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFTollFreeListResponse")
    public WsResponse getATFTollFreeList(
        @WebParam(name = "TFNumberList", targetNamespace = "")
        TfNumberList tfNumberList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param customProfileList
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFCustomProfileList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFCustomProfileList")
    @ResponseWrapper(localName = "getATFCustomProfileListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFCustomProfileListResponse")
    public WsResponse getATFCustomProfileList(
        @WebParam(name = "CustomProfileList", targetNamespace = "")
        CustomProfileList customProfileList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanGroupList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getSuperRoutePlanGroupList", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetSuperRoutePlanGroupList")
    @ResponseWrapper(localName = "getSuperRoutePlanGroupListResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetSuperRoutePlanGroupListResponse")
    public WsResponse getSuperRoutePlanGroupList(
        @WebParam(name = "SuperRoutePlanGroupList", targetNamespace = "")
        SuperRoutePlanGroupList superRoutePlanGroupList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param numberProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFNumberProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFNumberProfile")
    @ResponseWrapper(localName = "deleteATFNumberProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFNumberProfileResponse")
    public WsResponse deleteATFNumberProfile(
        @WebParam(name = "NumberProfile", targetNamespace = "")
        NumberProfile numberProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param customProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFCustomProfileDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFCustomProfileDetail")
    @ResponseWrapper(localName = "getATFCustomProfileDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFCustomProfileDetailResponse")
    public WsResponse getATFCustomProfileDetail(
        @WebParam(name = "CustomProfile", targetNamespace = "")
        CustomProfile customProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param numberProfileDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFNumberProfileDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFNumberProfileDetail")
    @ResponseWrapper(localName = "getATFNumberProfileDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFNumberProfileDetailResponse")
    public WsResponse getATFNumberProfileDetail(
        @WebParam(name = "NumberProfileDetail", targetNamespace = "")
        NumberProfileDetail numberProfileDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param numberProfile
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFNumberProfile", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFNumberProfile")
    @ResponseWrapper(localName = "updateATFNumberProfileResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFNumberProfileResponse")
    public WsResponse updateATFNumberProfile(
        @WebParam(name = "NumberProfile", targetNamespace = "")
        NumberProfile numberProfile,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param terminatingNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateATFTerminatingNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFTerminatingNumber")
    @ResponseWrapper(localName = "updateATFTerminatingNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.UpdateATFTerminatingNumberResponse")
    public WsResponse updateATFTerminatingNumber(
        @WebParam(name = "TerminatingNumber", targetNamespace = "")
        TerminatingNumber terminatingNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param activateSuperRoutePlanInGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "activateSuperRouteInGroup", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ActivateSuperRouteInGroup")
    @ResponseWrapper(localName = "activateSuperRouteInGroupResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ActivateSuperRouteInGroupResponse")
    public WsResponse activateSuperRouteInGroup(
        @WebParam(name = "ActivateSuperRoutePlanInGroup", targetNamespace = "")
        ActivateSuperRoutePlanInGroup activateSuperRoutePlanInGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanGroupDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getSuperRoutePlanGroupDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetSuperRoutePlanGroupDetail")
    @ResponseWrapper(localName = "getSuperRoutePlanGroupDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetSuperRoutePlanGroupDetailResponse")
    public WsResponse getSuperRoutePlanGroupDetail(
        @WebParam(name = "SuperRoutePlanGroupDetail", targetNamespace = "")
        SuperRoutePlanGroupDetail superRoutePlanGroupDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param tollFreeNumber
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteATFTollFreeNumber", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFTollFreeNumber")
    @ResponseWrapper(localName = "deleteATFTollFreeNumberResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.DeleteATFTollFreeNumberResponse")
    public WsResponse deleteATFTollFreeNumber(
        @WebParam(name = "TollFreeNumber", targetNamespace = "")
        TollFreeNumber tollFreeNumber,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanGroup
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createATFSuperRoutePlanGroup", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFSuperRoutePlanGroup")
    @ResponseWrapper(localName = "createATFSuperRoutePlanGroupResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.CreateATFSuperRoutePlanGroupResponse")
    public WsResponse createATFSuperRoutePlanGroup(
        @WebParam(name = "SuperRoutePlanGroup", targetNamespace = "")
        SuperRoutePlanGroup superRoutePlanGroup,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param superRoutePlanDetail
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFSuperRoutePlanDetail", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFSuperRoutePlanDetail")
    @ResponseWrapper(localName = "getATFSuperRoutePlanDetailResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFSuperRoutePlanDetailResponse")
    public WsResponse getATFSuperRoutePlanDetail(
        @WebParam(name = "SuperRoutePlanDetail", targetNamespace = "")
        SuperRoutePlanDetail superRoutePlanDetail,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param tollFreeSettingSS7
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "configATFTollFreeSettingSS7", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeSettingSS7")
    @ResponseWrapper(localName = "configATFTollFreeSettingSS7Response", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeSettingSS7Response")
    public WsResponse configATFTollFreeSettingSS7(
        @WebParam(name = "TollFreeSettingSS7", targetNamespace = "")
        TollFreeSettingSS7 tollFreeSettingSS7,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param tollFreeRouting
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "configATFTollFreeRouting", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeRouting")
    @ResponseWrapper(localName = "configATFTollFreeRoutingResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.ConfigATFTollFreeRoutingResponse")
    public WsResponse configATFTollFreeRouting(
        @WebParam(name = "TollFreeRouting", targetNamespace = "")
        TollFreeRouting tollFreeRouting,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param servicePlan
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.tollfree.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getATFServicePlan", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFServicePlan")
    @ResponseWrapper(localName = "getATFServicePlanResponse", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.tollfree.GetATFServicePlanResponse")
    public WsResponse getATFServicePlan(
        @WebParam(name = "ServicePlan", targetNamespace = "")
        ServicePlanSS7 servicePlan,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

}
