
package com.agnity.ngin.sms.webservice.tollfree;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TollFreeSmsServices", targetNamespace = "http://tollfree.webservice.sms.ngin.agnity.com/", wsdlLocation = "http://10.6.150.86:8003/tollfree-ws/TollFreeSmsServices/TollFreeSmsServices?wsdl")
public class TollFreeSmsServices_Service
    extends Service
{

    private final static URL TOLLFREESMSSERVICES_WSDL_LOCATION;
    private final static WebServiceException TOLLFREESMSSERVICES_EXCEPTION;
    private final static QName TOLLFREESMSSERVICES_QNAME = new QName("http://tollfree.webservice.sms.ngin.agnity.com/", "TollFreeSmsServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.150.86:8003/tollfree-ws/TollFreeSmsServices/TollFreeSmsServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOLLFREESMSSERVICES_WSDL_LOCATION = url;
        TOLLFREESMSSERVICES_EXCEPTION = e;
    }

    public TollFreeSmsServices_Service() {
        super(__getWsdlLocation(), TOLLFREESMSSERVICES_QNAME);
    }

    public TollFreeSmsServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOLLFREESMSSERVICES_QNAME, features);
    }

    public TollFreeSmsServices_Service(URL wsdlLocation) {
        super(wsdlLocation, TOLLFREESMSSERVICES_QNAME);
    }

    public TollFreeSmsServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOLLFREESMSSERVICES_QNAME, features);
    }

    public TollFreeSmsServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TollFreeSmsServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TollFreeSmsServices
     */
    @WebEndpoint(name = "TollFreeSmsServicesPort")
    public TollFreeSmsServices getTollFreeSmsServicesPort() {
        return super.getPort(new QName("http://tollfree.webservice.sms.ngin.agnity.com/", "TollFreeSmsServicesPort"), TollFreeSmsServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TollFreeSmsServices
     */
    @WebEndpoint(name = "TollFreeSmsServicesPort")
    public TollFreeSmsServices getTollFreeSmsServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tollfree.webservice.sms.ngin.agnity.com/", "TollFreeSmsServicesPort"), TollFreeSmsServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOLLFREESMSSERVICES_EXCEPTION!= null) {
            throw TOLLFREESMSSERVICES_EXCEPTION;
        }
        return TOLLFREESMSSERVICES_WSDL_LOCATION;
    }

}
