
package com.agnity.ngin.sms.webservice.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonSmsServices", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonSmsServices {


    /**
     * 
     * @param sessionId
     * @param authInfo
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "authenticateUser", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.AuthenticateUser")
    @ResponseWrapper(localName = "authenticateUserResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.AuthenticateUserResponse")
    public WsResponse authenticateUser(
        @WebParam(name = "AuthInfo", targetNamespace = "")
        AuthInfo authInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param uowJob
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "publishUnitOfWork", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.PublishUnitOfWork")
    @ResponseWrapper(localName = "publishUnitOfWorkResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.PublishUnitOfWorkResponse")
    public WsResponse publishUnitOfWork(
        @WebParam(name = "UowJob", targetNamespace = "")
        UowJob uowJob,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param unPublishedUowList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getUnPublishedUowList", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetUnPublishedUowList")
    @ResponseWrapper(localName = "getUnPublishedUowListResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetUnPublishedUowListResponse")
    public WsResponse getUnPublishedUowList(
        @WebParam(name = "UnPublishedUowList", targetNamespace = "")
        UnPublishedUowList unPublishedUowList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param unitOfWork
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteUnitOfWork", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.DeleteUnitOfWork")
    @ResponseWrapper(localName = "deleteUnitOfWorkResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.DeleteUnitOfWorkResponse")
    public WsResponse deleteUnitOfWork(
        @WebParam(name = "UnitOfWork", targetNamespace = "")
        UnitOfWork unitOfWork,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param uowStatus
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPublishedUOWStatus", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetPublishedUOWStatus")
    @ResponseWrapper(localName = "getPublishedUOWStatusResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetPublishedUOWStatusResponse")
    public WsResponse getPublishedUOWStatus(
        @WebParam(name = "UowStatus", targetNamespace = "")
        UowStatus uowStatus,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param accountInfo
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createOrganizationAccount", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.CreateOrganizationAccount")
    @ResponseWrapper(localName = "createOrganizationAccountResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.CreateOrganizationAccountResponse")
    public WsResponse createOrganizationAccount(
        @WebParam(name = "AccountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param unitOfWork
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "releaseUOWFromSession", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.ReleaseUOWFromSession")
    @ResponseWrapper(localName = "releaseUOWFromSessionResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.ReleaseUOWFromSessionResponse")
    public WsResponse releaseUOWFromSession(
        @WebParam(name = "UnitOfWork", targetNamespace = "")
        UnitOfWork unitOfWork,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param unitOfWork
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "createUnitOfWork", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.CreateUnitOfWork")
    @ResponseWrapper(localName = "createUnitOfWorkResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.CreateUnitOfWorkResponse")
    public WsResponse createUnitOfWork(
        @WebParam(name = "UnitOfWork", targetNamespace = "")
        UnitOfWork unitOfWork,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param accountInfo
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteOrganizationAccount", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.DeleteOrganizationAccount")
    @ResponseWrapper(localName = "deleteOrganizationAccountResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.DeleteOrganizationAccountResponse")
    public WsResponse deleteOrganizationAccount(
        @WebParam(name = "AccountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param authInfo
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "logoutUser", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.LogoutUser")
    @ResponseWrapper(localName = "logoutUserResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.LogoutUserResponse")
    public WsResponse logoutUser(
        @WebParam(name = "AuthInfo", targetNamespace = "")
        AuthInfo authInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param accountInfo
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getOrganizationAccount", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetOrganizationAccount")
    @ResponseWrapper(localName = "getOrganizationAccountResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetOrganizationAccountResponse")
    public WsResponse getOrganizationAccount(
        @WebParam(name = "AccountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param organizationAccountList
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getOrganizationList", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetOrganizationList")
    @ResponseWrapper(localName = "getOrganizationListResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetOrganizationListResponse")
    public WsResponse getOrganizationList(
        @WebParam(name = "OrganizationAccountList", targetNamespace = "")
        OrganizationAccountList organizationAccountList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param subscription
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "subscribeService", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.SubscribeService")
    @ResponseWrapper(localName = "subscribeServiceResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.SubscribeServiceResponse")
    public WsResponse subscribeService(
        @WebParam(name = "Subscription", targetNamespace = "")
        Subscription subscription,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param uowDetailList
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "getUOWStatusOnGC", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetUOWStatusOnGC")
    @ResponseWrapper(localName = "getUOWStatusOnGCResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.GetUOWStatusOnGCResponse")
    public WsResponse getUOWStatusOnGC(
        @WebParam(name = "UOWDetailList", targetNamespace = "")
        UowDetailList uowDetailList,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param accountInfo
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateOrganizationAccount", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.UpdateOrganizationAccount")
    @ResponseWrapper(localName = "updateOrganizationAccountResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.UpdateOrganizationAccountResponse")
    public WsResponse updateOrganizationAccount(
        @WebParam(name = "AccountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param unitOfWork
     * @param sessionId
     * @return
     *     returns com.agnity.ngin.sms.webservice.common.WsResponse
     */
    @WebMethod
    @WebResult(name = "WSResponse", targetNamespace = "")
    @RequestWrapper(localName = "selectUnitOfWork", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.SelectUnitOfWork")
    @ResponseWrapper(localName = "selectUnitOfWorkResponse", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", className = "com.agnity.ngin.sms.webservice.common.SelectUnitOfWorkResponse")
    public WsResponse selectUnitOfWork(
        @WebParam(name = "UnitOfWork", targetNamespace = "")
        UnitOfWork unitOfWork,
        @WebParam(name = "SessionId", targetNamespace = "")
        String sessionId);

}
