
package com.agnity.ngin.sms.webservice.common;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonSmsServices", targetNamespace = "http://common.webservice.sms.ngin.agnity.com/", wsdlLocation = "http://10.6.150.86:8003/common-ws/CommonSmsServices/CommonSmsServices?wsdl")
public class CommonSmsServices_Service
    extends Service
{

    private final static URL COMMONSMSSERVICES_WSDL_LOCATION;
    private final static WebServiceException COMMONSMSSERVICES_EXCEPTION;
    private final static QName COMMONSMSSERVICES_QNAME = new QName("http://common.webservice.sms.ngin.agnity.com/", "CommonSmsServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.150.86:8003/common-ws/CommonSmsServices/CommonSmsServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONSMSSERVICES_WSDL_LOCATION = url;
        COMMONSMSSERVICES_EXCEPTION = e;
    }

    public CommonSmsServices_Service() {
        super(__getWsdlLocation(), COMMONSMSSERVICES_QNAME);
    }

    public CommonSmsServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONSMSSERVICES_QNAME, features);
    }

    public CommonSmsServices_Service(URL wsdlLocation) {
        super(wsdlLocation, COMMONSMSSERVICES_QNAME);
    }

    public CommonSmsServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONSMSSERVICES_QNAME, features);
    }

    public CommonSmsServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonSmsServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonSmsServices
     */
    @WebEndpoint(name = "CommonSmsServicesPort")
    public CommonSmsServices getCommonSmsServicesPort() {
        return super.getPort(new QName("http://common.webservice.sms.ngin.agnity.com/", "CommonSmsServicesPort"), CommonSmsServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonSmsServices
     */
    @WebEndpoint(name = "CommonSmsServicesPort")
    public CommonSmsServices getCommonSmsServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.webservice.sms.ngin.agnity.com/", "CommonSmsServicesPort"), CommonSmsServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONSMSSERVICES_EXCEPTION!= null) {
            throw COMMONSMSSERVICES_EXCEPTION;
        }
        return COMMONSMSSERVICES_WSDL_LOCATION;
    }

}
